version: "3.8"

services:
  vidredact:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./videos:/data

  vidredact-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - ./videos:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
